-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jul 01, 2020 at 02:28 AM
-- Server version: 10.4.10-MariaDB
-- PHP Version: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mpgatesystem`
--

-- --------------------------------------------------------

--
-- Table structure for table `mpnewuser`
--

DROP TABLE IF EXISTS `mpnewuser`;
CREATE TABLE IF NOT EXISTS `mpnewuser` (
  `mpUserName` varchar(10) NOT NULL COMMENT 'auto generated RFID (soft)',
  PRIMARY KEY (`mpUserName`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `mpnewuser`
--

INSERT INTO `mpnewuser` (`mpUserName`) VALUES
('mpAdminGat'),
('mpAdminIT'),
('mpEntry001'),
('mpEntry002'),
('mpEntry003'),
('mpEntry004');

-- --------------------------------------------------------

--
-- Table structure for table `mpobjectscan`
--

DROP TABLE IF EXISTS `mpobjectscan`;
CREATE TABLE IF NOT EXISTS `mpobjectscan` (
  `mpColor` varchar(25) NOT NULL COMMENT 'color of vehicle',
  `mpPlate` varchar(10) NOT NULL COMMENT 'Liscnese Plate',
  `mpUserName` varchar(10) NOT NULL COMMENT 'autogenerated name for new sign in',
  `mpDateScanned` date NOT NULL DEFAULT current_timestamp() COMMENT 'date and time of scan',
  `mpStatus` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'incoming or outgoing vehicle',
  PRIMARY KEY (`mpPlate`(6)),
  UNIQUE KEY `rfidGenerated` (`mpUserName`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `mpregistered`
--

DROP TABLE IF EXISTS `mpregistered`;
CREATE TABLE IF NOT EXISTS `mpregistered` (
  `mpUserName` varchar(10) NOT NULL COMMENT 'get from new user',
  `mpLoginName` varchar(25) NOT NULL COMMENT 'create by user',
  `mpPasskey` varchar(8) NOT NULL COMMENT 'create by user',
  `mpEmail` varchar(100) NOT NULL COMMENT 'optional',
  PRIMARY KEY (`mpUserName`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
